#!/bin/bash

current_dir_path=$(pwd)

current_dir=$(basename "$current_dir_path")

if [ "$current_dir" != "fetchers" ]; then
  fetchers_path="$(dirname "$current_dir_path")/fetchers"
else
  fetchers_path="$current_dir_path"
fi

while read -r link; do
  eval link_to_pass="$link"
  ./fetch-match-using-hero-data.py "$link_to_pass"
done < "$fetchers_path/links.txt"
